<a href="https://colab.research.google.com/github/ravipranjal/OnlineGaming_DataMinig/blob/main/Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
cd /content/drive/MyDrive/Data\ Mining/Project/

/content/drive/MyDrive/Data Mining/Project

In [ ]:
ls

Analysis.ipynb  GamingStudy_data.csv

In [ ]:
##If pyspark 
# !pip install pyspark
# !pip install graphframes
# !pip install -U -q PyDrive
# !apt install openjdk-8-jdk-headless -qq
# !curl -L -o "/usr/local/lib/python3.7/dist-packages/pyspark/jars/graphframes-0.8.1-spark3.0-s_2.12.jar" https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.jar
# import os
# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"


# import pyspark
# from pyspark.sql import *
# from pyspark.sql.types import *
# from pyspark import SparkContext, SparkConf
# import pyspark.sql.functions as F
# from pyspark.sql.functions import explode
# from pyspark.ml.linalg import Vectors, SparseVector
# from pyspark.ml.clustering import LDA
# from pyspark.ml.feature import HashingTF, IDF, Tokenizer, CountVectorizer, StopWordsRemover
# from pyspark.ml.fpm import FPGrowth
# from graphframes import *

In [ ]:
#imports
import pandas as pd
import numpy as np
import seaborn
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('GamingStudy_data.csv',encoding='windows-1252')
df.head()

   S. No.    Timestamp  GAD1  ...  SPIN_T  Residence_ISO3  Birthplace_ISO3
0       1  42052.00437     0  ...     5.0             USA              USA
1       2  42052.00680     1  ...    33.0             USA              USA
2       3  42052.03860     0  ...    31.0             DEU              DEU
3       4  42052.06804     0  ...    11.0             USA              USA
4       5  42052.08948     2  ...    13.0             KOR              USA

[5 rows x 55 columns]